# Uncomment the next line to define a global platform for your project
platform :ios, '16'

target 'TerraVia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Add the Firebase pod for Google Analytics
  # pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod 'Firebase/AnalyticsWithoutAdIdSupport'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFunctions'

  # Pods for TerraVia

  target 'TerraViaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TerraViaUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16'
        if config.name == 'Development'
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_LDFLAGS'] << '-Xlinker -no_warn_duplicate_libraries'
          
          if target.name == 'FirebaseFirestoreInternal'
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-shorten-64-to-32'
          end
          
          if target.name == 'gRPC-Core'
            config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
            config.build_settings['OTHER_CFLAGS'] << '-Wno-macro-redefined'
          end
        end
      end
      
      target.shell_script_build_phases.each do |phase|
        if phase.name == 'Create Symlinks to Header Folders'
          phase.always_out_of_date = "1"
        end
      end
    end
  end

end
